# Generated by Django 3.2.5 on 2021-07-28 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookingapp', '0005_alter_reviews_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paymentmode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_No', models.CharField(max_length=100)),
                ('payment_mode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookingapp.paymentmode')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking', to='bookingapp.profile')),
            ],
        ),
    ]
