# Generated by Django 3.2.5 on 2021-07-28 11:40

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bookingapp', '0007_alter_cart_payment_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='property',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bookingapp.property'),
            preserve_default=False,
        ),
    ]
