# Generated by Django 3.2.5 on 2021-07-28 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingapp', '0011_alter_cart_payment_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmode',
            name='mode',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
