# Generated by Django 3.2.5 on 2021-07-28 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookingapp', '0012_alter_paymentmode_mode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='payment_mode',
        ),
        migrations.DeleteModel(
            name='Paymentmode',
        ),
    ]
