# Generated by Django 3.2.5 on 2021-07-28 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookingapp', '0013_auto_20210728_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='property',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bookingapp.property'),
        ),
    ]
