# Generated by Django 3.2.5 on 2021-07-28 12:52

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bookingapp', '0014_alter_cart_property'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paymentmode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='cart',
            name='property',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bookingapp.property'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cart',
            name='payment_mode',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bookingapp.paymentmode'),
            preserve_default=False,
        ),
    ]
