# Generated by Django 3.2.5 on 2021-07-28 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookingapp', '0015_alter_cart_property'),
        ('bookingapp', '0015_auto_20210728_1552'),
    ]

    operations = [
    ]
